# Generated by Django 5.2.10 on 2026-01-19 15:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bc_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bcmatch',
            options={'ordering': ['-matched_at'], 'verbose_name_plural': 'BC Matches'},
        ),
        migrations.AddField(
            model_name='bcmatch',
            name='admin_notes',
            field=models.TextField(blank=True, help_text='Internal notes about this match'),
        ),
        migrations.AddField(
            model_name='bcmatch',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bcmatch',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_matches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bcmatch',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Admin Approval'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected'), ('completed', 'Coffee Chat Completed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='bcmemberprofile',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bcmemberprofile',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_bc_members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bcmemberprofile',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Admin must approve before member appears in discovery'),
        ),
    ]
