# Generated by Django 5.2.10 on 2026-01-19 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bc_api', '0002_alter_bcmatch_options_bcmatch_admin_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bcapplicantprofile',
            name='role',
            field=models.CharField(choices=[('Freshman', 'Freshman'), ('Sophomore', 'Sophomore'), ('Junior', 'Junior'), ('Senior', 'Senior'), ('MBA1', 'MBA1'), ('MBA2', 'MBA2'), ('Graduate', 'Graduate')], max_length=50),
        ),
    ]
